
trigger:
- new-features

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Deploy
    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'TechPodDevOps'
          subscriptionId: '8a212724-2b09-4cf4-b15e-ea909d6bf920'
          action: 'Create Or Update Resource Group'
          resourceGroupName: 'rg'
          location: 'East US'
          templateLocation: 'Linked artifact'
          csmFile: 'main.bicep'
          deploymentMode: 'Incremental'
